### ISSUE TITLE
Add message from caster to cast message from bot

### ISSUE THREAD

**Issue by kosc** [Cuttlerat/pybot#16]
What do we have:
> User: ping kosc, do you have some time for monkey code?
> PyBot: @kosc

What do we want:
> User: ping kosc, do you have some time for monkey code?
> PyBot: @kosc, do you have some time for monkey code?

**Comment by Cuttlerat** [comment]
I think the best way is reply the origin message instead of repeating it

**Comment by kosc** [comment]
@Cuttlerat , OK, please describe that behavior in quotes like I did it in issue.
