### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by kosc** [Cuttlerat/pybot#22]
This project need in refactoring.
I think we should start from writing tests, but any suggestions are welcome.

**Comment by kosc** [comment]
@Cuttlerat assign this task to me, I can't.

**Comment by Cuttlerat** [comment]
I think first we need to remove all unused commands and save only the necessary commands like this:

https://github.com/Cuttlerat/pybot/blob/e0c6717e7448fbd165ad9163b6aea742bcbf9ad0/pybot.py#L814-L815
https://github.com/Cuttlerat/pybot/blob/e0c6717e7448fbd165ad9163b6aea742bcbf9ad0/pybot.py#L823-L824

I suggest creating a new branch with a version v2.0 and start our work from deleting unnecessary and rewriting the necessary commands. If you want to develop with TDD, then get started from tests.

**Comment by kosc** [comment]
I propose doctest for tests. @Cuttlerat what do you think about it?

**Comment by Cuttlerat** [comment]
Done by @CrownBerry. Thank you a lot!
