### ISSUE TITLE
Add commands for chatquotes 

### ISSUE THREAD

**Issue by Cuttlerat** [Cuttlerat/pybot#25]
`/chatquotes` - Random quote from chatquotes
`[Forwarded messages to bot]`
`/chatquotes` - Add quote only if user who send it in chatquote admins
`/chatquotes [ID]` - Send quote with this ID

If you can suggest a new command please leave a comment with a description of it and an example of use

**Comment by kosc** [comment]
Blocking task is now closed.

**Comment by Cuttlerat** [comment]
Won't implement
